apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: distedavim-backend
  name: distedavim-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distedavim-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: distedavim-backend
    spec:
      containers:
        - image: blazingh/nginx4prod:latest
          name: nginx
          ports:
            - containerPort: 80
        - image: blazingh/php4prod:1.8
          name: php
          env:
            - name: APP_NAME
              value: ""
            - name: APP_ENV
              value: ""
            - name: APP_KEY
              value: ""
            - name: DB_CONNECTION
              value: ""
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: ""
            - name: DB_DATABASE
              value: ""
            - name: DB_USERNAME
              value: ""
            - name: DB_PASSWORD
              value: ""
