apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: distedavim-frontend
  name: distedavim-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distedavim-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: distedavim-frontend
    spec:
      containers:
        - image: blazingh/nextjs4prod:1.2
          name: nextjs
