version: '3'
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
